[#274] Autoencoders unit and integration tests for each pipeline step
cyfronet-fid/recommender-system pull request #277
Opened 2021-11-10 13:25 UTC by Michal-Kolomanski

closes #274

2021-11-17 08:27 UTC, Michal-Kolomanski commented on recommender/engines/base/base_pipeline.py
> +        self.verbose = self.pipeline_config.get(VERBOSE, False)
But, on second consideration, shouldn't we stick with True here?

2021-11-17 12:43 UTC, Michal-Kolomanski commented on recommender/engines/autoencoders/inference/embedding_component.py
> -        print("Starting embedding...")
Keeping those print statements makes more sense with the new commands [GH](https://github.com/cyfronet-fid/recommender-system/blob/54bd5a994b72705c78c6a10a9408e1578f9761d9/recommender/commands.py#L68). Am I right?

2021-11-25 10:54 UTC, wujuu requested changes
Looks very good, some minor changes needed. We also need to separate other tests into unit and integration but that's a scope for another issue

2021-11-25 10:54 UTC, wujuu commented on tests/unit/engines/autoencoders/inference/test_embedding_component.py
> +    EmbeddingComponent()()
We should add some assertions here, for example if the dense tensors in the DB are of a certain shape and maybe some more

2021-11-25 17:07 UTC, wujuu approved these changes
Awesome, just squash, rebase, resolve conflicts and we are ready to close this PR

2021-11-26 09:14 UTC, merged