[#218] Create and configure log files
cyfronet-fid/recommender-system pull request #291
Opened 2021-12-15 17:55 UTC by Michal-Kolomanski

closes #218

2021-12-17 10:56 UTC, Michal-Kolomanski commented
The system of the logger was arranged as follows:
1) **console** - displays all events with a level of at least `INFO`. The level of detail in the logs may be adjusted using any of the two supplied loggers,
2) **file** -  to which all events with a level of at least `WARNING` are written.

Below I've included screenshots of the Celery console, the Server console, and the file that contains the logs following an exemplary request to the update endpoint.

Celery console:
![image](https://user-images.githubusercontent.com/47147210/146534132-8c3b8064-8ce4-4d06-96b4-e9f3d48b8d90.png)

Server console:
![image](https://user-images.githubusercontent.com/47147210/146534178-bde86bd6-2d1a-457a-8c2d-7acb8844f668.png)

File:
```
2021-12-17 11:43:29,076 | UPDATE_TASK | ERROR | There are not enough Users or Services | data_validation_step.py/valid_num_of_usr_and_srv [24]
2021-12-17 11:43:29,079 | UPDATE_TASK | ERROR | Exception has been raised. Training was unsuccessful. Aborting... | tasks.py/update [37]
Traceback (most recent call last):
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/tasks.py", line 25, in update
    AEPipeline(AUTOENCODERS_PIPELINE_CONFIG)()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/base/base_pipeline.py", line 71, in __call__
    data, details = step(data)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/autoencoders/training/data_validation_step.py", line 49, in __call__
    valid_num_of_usr_and_srv(collection, self.least_num_of_usr_srv)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/autoencoders/training/data_validation_step.py", line 25, in valid_num_of_usr_and_srv
    raise NotEnoughUsersOrServices()
recommender.errors.NotEnoughUsersOrServices

```

2021-12-17 11:26 UTC, Michal-Kolomanski commented
Using one of two prepared loggers are recommended:
1) `Root `- which is can be obtained by calling `get_logger("")` and produces logs with less detail - usually preferred in `INFO` logs,
2) `UPDATE TASK` - which is can be obtained by calling `get_logger()`,and contains a more detailed description of events in the logs - usually preferred in >=`WARNING` logs.

2021-12-17 12:28 UTC, Michal-Kolomanski commented
@wujuu @JanKapala 
Please test this pull request in your local environment. Especially in `migrations`, `train`, `/update`

2021-12-23 12:26 UTC, JanKapala requested changes
Well done, logging is beautiful. It works for `flask migrate` tasks and when `update` endpoint is triggered, but when I've used `flask train all` then there were no logs in recommender._ogs.log file and in the celery worker console.

2022-01-03 08:28 UTC, Michal-Kolomanski commented
> Well done, logging is beautiful. It works for `flask migrate` tasks and when `update` endpoint is triggered, but when I've used `flask train all` then there were no logs in recommender_logs.log file and in the celery worker console.

Thanks for the review.
We only support task `/update` in the Celery console, thus nothing should be logged there while performing a local training.
Furthermore, only events above `INFO` level are logged into the file `recommender_logs.log` (e.g. warning). Are you sure that there were some events during training that should be logged but they weren't? 

For me it seems to work just fine:
![image](https://user-images.githubusercontent.com/47147210/147911148-d76ec9a6-ed8a-4727-b24b-5ba7bf7e884a.png)

2022-01-03 10:49 UTC, Michal-Kolomanski commented
> > Well done, logging is beautiful. It works for `flask migrate` tasks and when `update` endpoint is triggered, but when I've used `flask train all` then there were no logs in recommender_logs.log file and in the celery worker console.
> 
> Thanks for the review @JanKapala. We only support task `/update` in the Celery console, thus nothing should be logged there while performing a local training. Furthermore, only events above `INFO` level are logged into the file `recommender_logs.log` (e.g. warning). Are you sure that there were some events during training that should be logged but they weren't?
> 
> For me it seems to work just fine: ![image](https://user-images.githubusercontent.com/47147210/147911148-d76ec9a6-ed8a-4727-b24b-5ba7bf7e884a.png)

Now I realize that there is an issue with logging when FLASK ENV=development is used. I am working on it.

2022-01-04 10:25 UTC, Michal-Kolomanski commented
After some workaround, I discovered a less-than-ideal but workable solution which I described here as a comment:  [Stack Overflow](https://stackoverflow.com/questions/65508074/when-flask-env-development-werkzeug-does-not-log-http-requests/70576777#70576777)
Now, the only difference between logging in production and development environment should be the initial log containing information about the server's IP address.

Production:
![image](https://user-images.githubusercontent.com/47147210/148044117-a0c50750-3dd6-4cee-9264-552e026df0d1.png)

Development:
![image](https://user-images.githubusercontent.com/47147210/148045027-b467ea41-e6ea-4495-b55b-eec958d786a2.png)

2022-01-17 16:36 UTC, JanKapala approved these changes

2022-01-17 16:58 UTC, merged