[#391] Add AAI Token to the user model
cyfronet-fid/recommender-system pull request #394
Opened 2022-08-18 13:12 UTC by wujuu

2022-08-22 07:45 UTC, Michal-Kolomanski requested changes
Unfortunately, the scope of the ticket is larger. "Adjust models and code regarding introducing the AAI token", please also change our code in such a way that we will be using **uid** or **user_id** for identifying users. There is also open question: shouldn't we use only **uid** for identifying users?

2022-08-22 07:45 UTC, Michal-Kolomanski commented on recommender/api/schemas/database_dump/user.py
> +            example="abcdefghijklmnop",
This example is misleading and may cause confusion.
An example of an uid can be: 64-characters@egi.eu
General structure: [id-hex]@[sso-provider]

2022-08-22 07:45 UTC, Michal-Kolomanski commented on recommender/api/schemas/database_dump/user.py
> +        "aai_token": fields.String(
I believe it should be named "uid" not aai_token - but that's my bad. The title of the ticket was misleading. Sorry for that. Please change that everywhere

2022-08-22 08:09 UTC, wujuu commented
I don’t understand why we cannot use user-id for the existing models and only use uid (aai-token) for the new engines that require this new identification scheme

2022-08-22 08:46 UTC, Michal-Kolomanski commented
> I don’t understand why we cannot just use user-id (like we’ve been doing this whole time) for the existing models and only use uid (aai-token) for the new engines that require this new identification scheme

We have a complete understanding here, that's how it should be done. What I only suggested that still should be done was the ability to use the uid (in endpoint / recommendations) which implies: 
1) correctly identify the user based on his uid in recommendations pipelines
2) receive relevant recommendations for the user

But I can agree that this can be the scope of the next ticket. If you want, we can merge this ticket (after aai_token -> uid) and work on the above feature in the next ticket

2022-08-27 10:36 UTC, wujuu commented
Made a change to intake aai_token or user_id as a user identification type. Only tested through unit tests for now.
and BTW:
Can we actually not rename the field? user_id and uid seem way to similar in my opinion

2022-08-29 16:42 UTC, Michal-Kolomanski requested changes
LGTM but please change aai_token to aai_uid or present some more arguments for the name aai_token

2022-08-29 16:42 UTC, Michal-Kolomanski commented on recommender/api/schemas/database_dump/user.py
> +        "aai_token": fields.String(
**aai_uid** in my opinion will be better

2022-08-29 16:42 UTC, Michal-Kolomanski commented on recommender/api/schemas/database_dump/user.py
> +            example="abcdefghijklmnop",
An example may be better. Look [recommender/api/schemas/recommendation.py](https://github.com/cyfronet-fid/recommender-system/pull/394/files#diff-a395fd459f377dc7e7a1575bf337d5e2bb9a7eafbbd5e77070ce7d9b802fbbe1)

            example="zooehewplbfxqtnxpspzsgrmeadoynbygyvisuvzst"
            + "dgenzxklzuwfdjndtzitiz@egi.eu",

2022-08-29 16:42 UTC, Michal-Kolomanski commented on recommender/api/schemas/recommendation.py
> +        "aai_token": fields.String(
aai_uid

2022-08-29 16:42 UTC, Michal-Kolomanski commented on recommender/api/schemas/user_action.py
> +        "aai_token": fields.String(
aai_uid

2022-08-29 16:42 UTC, Michal-Kolomanski commented on recommender/engines/base/base_inference_component.py
> +        Get the user from the context using either a user_id or an aai_token.
aai_uid

2022-09-07 06:48 UTC, wujuu commented
Ok changes the `aai_token` to `aai_uid`

2022-09-12 16:14 UTC, Michal-Kolomanski approved these changes
LGTM :clap:

2022-09-12 16:14 UTC, Michal-Kolomanski commented on recommender/services/deserializer.py
> +        if aai_uid and not user_id:
Assumption that if aai_token is passed, user_id is not. Just thinking loudly. No action is required.
So in the MP we cannot pass also aai_token

2022-09-13 10:27 UTC, Michal-Kolomanski commented
1 thing only - please add changelog

2022-09-16 07:16 UTC, merged